var f1 = "gallery/";
var f2 = "gallery/thumbs/";

CGallery.data = [
    {
        image: f1 + 'P_0050_Twins.jpg',
        thumb: f2 + 'P_0050_Twins.jpg',
        title: 'The first line is the title',
        descr: 'The second line is the description. Image 1: Twins !',
        outerBorders: [.005,"#d1d0d5"] //3f5606 [0.01,"black",0.01,"white",0.01,"black",0.02,"white"]
    },
    {
        image: f1 + 'P_0163_RightFlower.jpg',
        thumb: f2 + 'P_0163_RightFlower.jpg',
        descr: 'This image has inside and outside borders generated by the ClusterGallery',
        outerBorders: [.02,"#b59402"],
        innerBorders: [.02,null,0.5, .01,"#ffd103",0.31]
    },
    {
        image: f1 + 'ChaosMushrooms_0010.jpg',
        thumb: f2 + 'ChaosMushrooms_0010.jpg',
        descr: 'Chaos Mushrooms',
        outerBorders: [0.005,"#d2d3b4",0.04,"#948e6e"]
    },
    {
        image: f1 + 'P_0014_tulip.jpg',
        thumb: f2 + 'P_0014_tulip.jpg',
        descr: 'A tulip ;)',
        outerBorders: [.03,"black", .005, "#618148"] //a30100 .01,"#d2caa6", .02, "#618148"
    },
    {
        image: f1 + 'P_0185_WhiteFlower.jpg',
        thumb: f2 + 'P_0185_WhiteFlower.jpg',
        descr: 'Border code: [0.02,"#937b4a",0.01,"black",0.004,"#937b4a"]',
        outerBorders: [0.003,"#ccc", .02,"#404813",0.01,"black",0.004,"#937b4a"]
    },
    {
        image: f1 + 'P_0095_MoreFlowers.jpg',
        thumb: f2 + 'P_0095_MoreFlowers.jpg',
        descr: 'More flowers',
        outerBorders: [0.008,"black",0.004,"#bbb",0.01,"black",0.02,"#373f10"]
    },
    {
        image: f1 + 'P_0005_Blue.jpg',
        thumb: f2 + 'P_0005_Blue.jpg',
        descr: 'The last image of the demo gallery',
        outerBorders: [0.005,"black",0.01,"#562b94",0.02,"#6740b5"],
        innerBorders: [.01,null,0.5, .01,"#6740b5",0.7]
    }
];

// Parameters: ( To use remove // before the line and change the value before the ; )

CGallery.canvasBackground = "#000"; // define the canvas backgroundcolor, IE 6 & 7 have problems with a transparent background. Default value = null

// CGallery.canvasBorder = 10; // inside border inside the canvas
// CGallery.activeImage = 0;   // The first image to show. 0 = the first image

// CGallery.arrowScale = 1;    // default = 1 = 100%, 2= 200%, ...
// CGallery.arrowSpacing = 10;  // space between image & arrow
// CGallery.arrowTransparency = 0.2;
// CGallery.arrowPosition = 0; // 0 = border, 1 = next to the image
// CGallery.arrowColor = "#000";
// CGallery.arrowBackColor = "#fff";

// CGallery.showFullScreenIcon = false;  // Can the viewer go to full screen mode?

// CGallery.textSize = "17px";
// CGallery.textColor = "#000";
// CGallery.textBackground = "#fff";
// CGallery.textBoxHeight = 40;
// CGallery.textBoxTransparency = 0.3;
CGallery.defaultTitle = "\u00A9 Gunther Willems";
// CGallery.defaultDescription = "";
// CGallery.textPosition = "bottom";  // none | top | middle | bottom | topmiddle | bottommiddle | free, if free set the value in textY
// CGallery.textAlways = true;  // if false, the text will show when the mousecursor is over the image
// CGallery.textY = -1;  // position of textbox if textPosition="free", default value -1

// CGallery.outerBorders = [0.01,"white",0.01,"black",0.03,"white"];  // default border around the images. The number of borders is unlimited. Syntax: [size percent, color, size percent, color, ...], for no borders: []

// CGallery.showSlideshowIcon = false; //Can the viewer start/stop the slideshow?
// CGallery.autoSlideshow = true; // start the slideshow automatically
// CGallery.nextImageSpeed = 3000; // in milliseconds
// CGallery.useImagesAsThumbs = true; // if no thumb is defined for an image, use the full image
// CGallery.thumbSize = "50px"; // used if useImagesAsThumbs is true

// Initialize the gallery:
window.onload = CGallery.Init;